### ISSUE TITLE
Remove duplicate records

### ISSUE THREAD

**Issue by skeetidot** [skeetidot/homestead-hebrews#1]

**Comment by tammyalexandra** [comment]
Updated in ef9fd0e64b7fa6a3c1c5f424133b854d76546fe1 .

Only removed those where the same address appears in both entries.  This leaves a small group where a person appears twice, but with a different address in each case.

Some thoughts as I reviewed these:
1.  It's interesting how *you* were the one who figured out some of these duplicates.  For ex Samuel Moranz in 1902:  530 Heisel st vs. Heisel st and P V & C R R.
2.  For cases where there is a different profession in each one -- for ex Harry Pollack in 1902:  fruit dealer vs. confectioner -- I merged the profession.  Not sure if that messes things up on your end.
