### ISSUE TITLE
Better display for "Multiple records" popups

### ISSUE THREAD

**Issue by tammyalexandra** [skeetidot/homestead-hebrews#10]
I'd like for the pop-ups that display for points pertaining to multiple people to be more informative without having to click on the dots to see all the residents.  Is it possible to list the names of the people who live there?

**Comment by skeetidot** [comment]
This should be possible. See lines 1554-1608 in main.js.

**Comment by skeetidot** [comment]
I updated the tooltip heading to show the matched address and updated the tooltip content to show all people at the current address in the current year

See https://skeetidot.github.io/homestead-hebrews/home.html.

**Comment by tammyalexandra** [comment]
This looks good.  I pushed it to production.  Thanks!
